
POST http://localhost:3001/add-lab
Content-Type: application/json

{
  "nama_Labor":"Laboratorium of Enterprise Application",
  "deskripsi":"Laboratorium of Enterprise Application (LEA) adalah salah satu labor yang ada pada jurusan Sistem Informasi Universtas Andalas (Unand) yang bergerak dalam bidang penelitian dan penggunaan teknologi dan layanan sistem informasi pada organisasi atau perusahaan."
}
###
GET http://10.44.11.241:3000/

###
POST http://localhost:3001/getuserbytoken
Content-Type: application/json

{
  "token":"700a95db0d7e99db45c6cb20d889c89b25153d450df11bda2949977a6686af6f19b30e01b38571013e2d7fafdc809c85b56c41340c2670ea1d82611921da8eee02479cf839fe9eb70ff6f5e1de6cd8c4b738b2d549d75c6ec716e49bd34c733c833a13d7c70fa22cb386bd3c1dc4457439b6bbeab451a9c4b277c7322b5d677c9d9745a4f1d6ba7bd7bfac37225498a2574573a1012d9d9285e88db5058e95124c045a21b00fe05eb44b7de5d45c23ce"
}
###
DELETE  http://localhost:3001/delete-lab/
Content-Type: application/json

{
  "id":"75afa762-e01f-44b5-8f97-426fa8965b3e"
}

###
POST http://localhost:3001/login-web
Content-Type: application/json

{
  "nim":"2011522007",
  "password":"Ayam"
}

###

POST http://localhost:3001/register
Content-Type: application/json

{
  "idLabor":"a8f3b29d-ee61-436d-a267-6acfd22f1740",
  "nim":"2011522014",
  "email":"agasdasds3di@gmail.com",
  "nomor_asisten":"LEA.V.14.SI",
  "jenisPengguna":"Asisten",
  "AksesRole":"User",
  "nama":"Hendra Wijaya Kusuma",
  "password":"Satu123@",
  "status":"Lulus",
  "nomor_hp":"081270403357",
  "tempat_lahir":"Lubuk Basung",
  "tanggal_lahir":"01/08/2001",
  "JenisKelamin":"Pria",
  "alamat":"Kota Padang",
  "angkatan":"2020"
}
###

POST http://localhost:3001/add-pendaftar
Content-Type: application/json

{
  "idUsers":"419734f3-5711-45a8-bb7b-75bcd0cc334e",
  "idKegiatan":"7675998e-f68a-4b31-b162-ad348c7ed33c",
  "idRecruitment":"42b84e31-55cd-4cb0-ba6f-d5e55503c711",
  "tanggal_daftar":"2024-05-22T05:12:55.000Z"
}

###
POST http://localhost:3001/add-pendaftar
Content-Type: application/json

{
  "idUsers":"419734f3-5711-45a8-bb7b-75bcd0cc334e",
  "idKegiatan":"7675998e-f68a-4b31-b162-ad348c7ed33c",
  "idRecruitment":"42b84e31-55cd-4cb0-ba6f-d5e55503c711",
  "tanggal_daftar":"2024-05-22T05:12:55.000Z"
}